### ISSUE TITLE
Поправить футер

### ISSUE THREAD

**Issue by Blackk88** [Softocean/landing#21]
![Image](https://user-images.githubusercontent.com/108989350/263467999-afd6e089-229e-4c53-b114-ff965e00edd3.png)

Исправить верстку футера

Definition of done: 
- градиент фона футера должен быть светлее, текст на нем должен быть читаемым
- добавить адаптивность (не должно быть горизонтального скрола)

**Comment by RinVeber** [comment]
1. градиент висит только на тексте в футере. 
На бэкграунде его нет в футере.


![Image](https://github.com/Softocean/landing/assets/96541093/459f4066-1ece-4578-ab04-635cb07f3452)

**Comment by RinVeber** [comment]
2. Пофиксил адаптивность в футере.


![Image](https://github.com/Softocean/landing/assets/96541093/631c82a8-8c1f-4475-b5b2-87d16804f0ce)

**Comment by RinVeber** [comment]
Горизонтальный скролл появляется из-за блока с текстом в фидбеке


![Image](https://github.com/Softocean/landing/assets/96541093/23c897af-0c6c-4708-a234-80d45855fea3)
