### ISSUE TITLE
Добавить Header

### ISSUE THREAD

**Issue by Blackk88** [Softocean/landing#4]
### Добавить компонент header

![Image](https://user-images.githubusercontent.com/108989350/260282947-192c3554-dbd5-4ca1-bd68-523546b9d6c1.png)

[Figma](https://www.figma.com/file/2AfVZvEgeyxNHO9IOEXT9X/SoftOcean-FINAL?type=design&node-id=3062-14525&mode=dev)

**Comment by apant94** [comment]
Создан ПР https://github.com/Softocean/landing/pull/34
