### ISSUE TITLE
Добавить active link

### ISSUE THREAD

**Issue by Blackk88** [Softocean/landing#42]
Нужно добавить отображении активной ссылки, таким же стилем как сейчас отображается ссылка при наведении. 
Активный статус проверять по роуту на котором находимся. Должно применяться к ссылкам в footer и header

![Screenshot 2023-09-17 at 12 40 31 PM](https://github.com/Softocean/landing/assets/108989350/fcae6f1d-2337-4e9f-bc04-334025d6003f)

**Comment by apant94** [comment]
https://github.com/Softocean/landing/pull/43
